# Create web application database with proxy and database.
---

version: "3.3"

services:
  database:
    container_name: database
    env_file:
      - ./env/database.env
    image: crunchydata/crunchy-postgres:centos7-10.3-1.8.2
    ports:
      - "5432:5432"
    networks:
      - cluster
    volumes:
      - pgdata:/pgdata
  jdbcwar:
    container_name: jdbcwar
    env_file:
      - ./env/jdbcwar.env
    image: dev/jdbcwar
    ports:
      - "8081:8080"
      - "8001:8000"
    networks:
      - cluster
  simplewar:
    container_name: simplewar
    env_file:
      - ./env/simplewar.env
    image: dev/simplewar
    ports:
      - "8080:8080"
      - "8000:8000"
    networks:
      - cluster
  proxy:
    container_name: proxy
    image: dev/proxy
    ports:
      - "443:18443"
      - "80:18080"
    networks:
      - cluster

networks:
  cluster:
volumes:
  pgdata:


